### ISSUE TITLE
Rewrite Milestone 1 todo

### ISSUE THREAD

**Issue by Behold3th** [BanklessDAO/bountybot-#1]
Collating Todo items. 
We're still at the stage on the bot rewrite where individual issues for each bug fix/feature improvement is more of a hassle. 
edit: Striking out todo items as they get resolved, thanks @tescher for the call out

@tescher succinctly captured everything on my radar and more:

> ~1. I assume the hard-coded guild id  needs to be fixed, either reading from the DB or a list in the .env file~
> ~2. 'Please go to #🧀-bounty-board to take action.' is hard-coded. Should this name come from a channel ID in .env?~
> 3. Some other TODOs I saw, like the board URL
> ~4. Can we change the name "HashId" in the view to "Bounty Id"? The /bounty command calls it that.~
> 
> Other things I saw off the bat:
> ~1. 'no or 'skip' doesn't work for the date, even though the instructions reference them.~
> ~2. If you don't publish right away, the "Bounty Bot is thinking..." never goes away.~
> In general, since this is a rewrite, a thorough unit test probably needs to be developed and completed. Write down all options and branches, and systematically run through them all. I don't have time to do that, but it should be done.
> One other thing I just saw - I put 2022-01-31 as the deadline date, and it is showing as Sunday, January 30, 2022. Timezone issue?

Some items on my list: (not in order of priority)
1.~deleting draft in create DMs has weird behavior (screenshot below)~
<img width="1019" alt="Screen Shot 2022-01-11 at 12 43 08 AM" src="https://user-images.githubusercontent.com/85538143/148888050-2d96fd42-1a7c-4c44-8ee7-7dd7547968c8.png">
3. ~Reconsider out draft --> open flow. Currently there isn't a sensible way to stop at draft (perhaps that's desired to force users through the full create and publish flow?) and pick it up later.~
4. Db name and collection names are currently hardcoded
5. List activity works, but send an ephemeral fail fast in the command context channel
6.~gating auth handler allows non-allowlisted roles to claim a bounty~
7. delete error seen below: 
<img width="1019" alt="Screen Shot 2022-01-13 at 1 31 32 AM" src="https://user-images.githubusercontent.com/85538143/149277806-10be8723-7c58-4c6b-868d-cd48673b32c5.png">

**Comment by tescher** [comment]
The ones struck-out, are they done?

**Comment by Behold3th** [comment]
This rewrite is in production.
