### ISSUE TITLE
improvement: after bounty is created, automatically refresh list

### ISSUE THREAD

**Issue by Behold3th** [BanklessDAO/bountybot-#50]
Currently, once a bounty is created, a user will need to click "Back to List" and then "refresh" to see the created bounty on the main list of bounties. The second action with hitting "refresh" will be confusing for users - they aren't aware of the technical challenge we have with doing this, and it's an un-intuitive UI

After a bounty is created, I'd like the list to be automatically refreshed so that the user doesn't have to hit "refresh"

**Comment by tescher** [comment]
Fixed in #57
